name: Build backend

on:
  push:
    branches:
      - main
    paths: backend/**/*
  workflow_dispatch: 

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub 
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          sudo docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/cmm-backend:latest -f ./backend/Dockerfile ./backend
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/cmm-backend:latest
