name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run docker-compose
        run: |
          cd /home/ubuntu/PROD-PRODlenka
          git pull
          sudo docker compose pull
          sudo docker compose up -d
