name: Deploy frontend

on:
  push:
    paths: frontend/**/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: 'frontend'
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: cd frontend 
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Download dependency
        run: pnpm install
      - name: Build project
        run: pnpm build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist