name: Build frontend

on:
  push:
    paths: frontend/**/*
  workflow_dispatch: 

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub 
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/cmm-frontend:latest -f ./frontend/Dockerfile ./frontend
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/cmm-frontend:latest